<your project name>:
  outputs:
    dev:
      account: rja95216
      database: DS5111_DB
      password: dbtorbust 
      role: DS5111_DBT
      schema: LAB01_uxt5qb
      threads: 1
      type: snowflake
      user: uxt5qb@virginia.edu
      warehouse: COMPUTE_WH
  target: dev
